packages:
  darwin:
    brews:
      # Basics
      - "coreutils"
      - "git"
      - "mise"
      - "ruby-build"
      - "uv"

      - "atuin"
      - "bat"
      - "eza"
      - "fd"
      - "fish"
      - "fzf"
      - "gh"
      - "graphviz"
      - "hl"
      - "neovim"
      - "ripgrep"
      - "shellcheck"
      - "shfmt"
      - "starship"
      - "tree-sitter-cli"
      - "try-rs"
      - "zellij"
      - "zoxide"
    casks:
      - "claude"
      - "claude-code"
      - "docker-desktop"
      - "ghostty"
      - "google-chrome"
      - "visual-studio-code"
      - "zed"
