packages:
  darwin:
    brews:
      - "coreutils"
      - "git"
      - "mise"
      - "neovim"
      - "ruby-build"

      - "fish"
      - "starship"
      - "atuin"
      - "zoxide"

      - "shellcheck"
      - "shfmt"
    casks:
      - "claude"
      - "docker-desktop"
      - "ghostty"
      - "google-chrome"
      - "visual-studio-code"
      - "zed"
