packages:
  darwin:
    brews:
      - "coreutils"
      - "git"
      - "mise"
      - "ruby-build"

      - "fish"
      - "starship"
      - "atuin"
      - "zoxide"
    casks:
      - "claude"
      - "ghostty"
      - "google-chrome"
      - "visual-studio-code"
      - "visual-studio-code"
      - "zed"
